# frozen_string_literal: true

require 'bundler'

Bundler::GemHelper.install_tasks

require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)

require 'rubocop/rake_task'
RuboCop::RakeTask.new(:rubocop)

task test: :spec
task lint: :rubocop
task default: %i[spec lint]
